### ISSUE TITLE
Search is broken on lists.lrug.org

### ISSUE THREAD

**Issue by andyw8** [lrug/lrug.org#43]
I wasn't sure of the best way to report this, but searching on http://lists.lrug.org/pipermail/chat-lrug.org/ fails with:

> ht://Dig error
> 
> htsearch detected an error. Please report this to the webmaster of this site by sending an e-mail to: mailman@listserver-else.dreamhost.com The error message is:
> 
> Unable to read word database file '/dh/mailman/else/archives/private/chat-lrug.org/htdig/db.words.db'
> Did you run htdig?

**Comment by andyw8** [comment]
Also, I'm not sure if this is related, but some messages seem to be missing from the archive – the January 2016 page appears to only cover Jan 22 to Jan 28.

**Comment by tomstuart** [comment]
Cheers Andy. I think this is pretty much out of our control since the mailing list archive is hosted, but @h-lame can probably give them a kick.

The ultimate solution is to replace the mailing list software with the amazing thing that @lazyatom may or may not be building…

**Comment by h-lame** [comment]
Hi @andyw8 - yes it's a hosted service, so I'll raise a support ticket with them.  Thanks for bringing it to our attention.  Regarding the missing messages, it's possible they're just not in the db for some reason and so we'll never get them into the archive :(  There is spotty coverage in the archives for most of last year because of issues at the host.

**Comment by h-lame** [comment]
Search is (currently) not actually broken on the lists subdomain.  It comes and goes as far as I'm aware, and it's definitely not configured 100% correctly, because you get a load of missing images.  However, it's a hosted service that we have little control over, and it's working for now, so I'm gonna call this issue closed (after a 3.5 year wait, what great service!).
